"""fff

Revision ID: 2e8356d7d5bd
Revises: c1cab8947573
Create Date: 2024-12-30 16:32:52.671424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8356d7d5bd'
down_revision: Union[str, None] = 'c1cab8947573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'a_point',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('requests', 'b_point',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'b_point',
               existing_type=sa.String(length=200),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('requests', 'a_point',
               existing_type=sa.String(length=200),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
